using System;

namespace Diffie_Hellman
{
    class Program
    {
        static void Main(string[] args)
        {
            int prime = 29;
            int g = 2;

            //Alice

            Random rnd = new Random();
            long privA = rnd.Next(1, 10);
            Console.WriteLine("Private secret generated by Alice: " + privA);
            long pubA = LongPow(g, privA) % prime;
            Console.WriteLine("Public key generated by Alice: " + pubA);

            //Bob

            long privB = rnd.Next(1, 10);
            Console.WriteLine("Private secret generated by Bob: " + privB);
            long pubB = LongPow(g, privB) % prime;
            Console.WriteLine("Public key generated by Bob: " + pubB);

            //Result

            Console.WriteLine("Alice computed shared secret: " + LongPow(pubB, privA) % prime);
            Console.WriteLine("Bob computed shared secret: " + LongPow(pubA, privB) % prime);

            Console.ReadLine();
        }

        static long LongPow(long x, long pow)
        {
            long l = 1;
            while (pow != 0)
            {
                if ((pow & 1) == 1)
                    l *= x;
                x *= x;
                pow >>= 1;
            }
            return l;
        }
    }
}